name: Close Stale Issues
on:
  # schedule:
  # - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      stale-days: 30
      close-days: 7
      stale-label: stale
      stale-exempt-label: stale-exempt
      only-label: more info needed
    steps:
    - uses: actions/stale@v4.1.1
      with:
        stale-issue-label: ${{ env.stale-label }}
        exempt-issue-labels: ${{ env.stale-exempt-label }}
        only-labels: ${{ env.only-label }}
        days-before-pr-stale: -1
        days-before-pr-close: -1
        days-before-stale: 1
        stale-issue-message: "This issue is now marked as 1 day old due to there being no activity on it for the past 1 days and being labelled 1. Unless the 1 label is removed or the issue is commented on, this will be closed in1 days. If you would like to make this issue exempt from getting stale, please remove the '${{ env.only-label }}' and '${{ env.stale-label }}' labels or add the '${{ env.stale-exempt-label }}' label"
        days-before-close: 1
        close-issue-message: "This issue is now closed due to there being no activity on it for the past 1 days since being marked as 1."
        operations-per-run: 500
        close-issue-reason: not_planned
